// <auto-generated />
using System;
using HorsesForCourses.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorsesForCourses.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911110427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("HorsesForCourses.Domain.Coaches.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("HorsesForCourses.Domain.Courses.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedCoachId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCoachId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("HorsesForCourses.Domain.Coaches.Coach", b =>
                {
                    b.OwnsMany("HorsesForCourses.Domain.Skills.Skill", "skills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CoachId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Value");

                            b1.HasKey("Id");

                            b1.HasIndex("CoachId", "Value")
                                .IsUnique();

                            b1.ToTable("CoachSkills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CoachId");
                        });

                    b.OwnsOne("HorsesForCourses.Domain.Coaches.CoachEmail", "Email", b1 =>
                        {
                            b1.Property<int>("CoachId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("CoachId");

                            b1.ToTable("Coaches");

                            b1.WithOwner()
                                .HasForeignKey("CoachId");
                        });

                    b.OwnsOne("HorsesForCourses.Domain.Coaches.CoachName", "Name", b1 =>
                        {
                            b1.Property<int>("CoachId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("CoachId");

                            b1.ToTable("Coaches");

                            b1.WithOwner()
                                .HasForeignKey("CoachId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("skills");
                });

            modelBuilder.Entity("HorsesForCourses.Domain.Courses.Course", b =>
                {
                    b.HasOne("HorsesForCourses.Domain.Coaches.Coach", "AssignedCoach")
                        .WithMany("AssignedCourses")
                        .HasForeignKey("AssignedCoachId");

                    b.OwnsMany("HorsesForCourses.Domain.Skills.Skill", "requiredSkills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CourseId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Value");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseId", "Value")
                                .IsUnique();

                            b1.ToTable("CourseRequiredSkills", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("HorsesForCourses.Domain.Courses.CourseName", "Name", b1 =>
                        {
                            b1.Property<int>("CourseId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("HorsesForCourses.Domain.Courses.Period", "Period", b1 =>
                        {
                            b1.Property<int>("CourseId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("PeriodEnd");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("PeriodStart");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsMany("HorsesForCourses.Domain.Courses.TimeSlots.TimeSlot", "timeSlots", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CourseId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Day")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Day");

                            b1.Property<int>("End")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EndHour");

                            b1.Property<int>("Start")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StartHour");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseId");

                            b1.ToTable("CourseTimeSlots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("AssignedCoach");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("requiredSkills");

                    b.Navigation("timeSlots");
                });

            modelBuilder.Entity("HorsesForCourses.Domain.Coaches.Coach", b =>
                {
                    b.Navigation("AssignedCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
